2020-05-28 09:08:57,757 ERROR 16980 nodejs.unhandledRejectionError: ER_NO_SUCH_TABLE: Table 'egg-test.userz' doesn't exist
    at Query.Sequence._packetToError (C:\houfei-file\project\egg-example\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\houfei-file\project\egg-example\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\houfei-file\project\egg-example\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\houfei-file\project\egg-example\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\houfei-file\project\egg-example\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\houfei-file\project\egg-example\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\houfei-file\project\egg-example\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\houfei-file\project\egg-example\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\houfei-file\project\egg-example\node_modules\mysql\lib\Pool.js:199:23)
    at C:\houfei-file\project\egg-example\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\houfei-file\project\egg-example\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\houfei-file\project\egg-example\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\houfei-file\project\egg-example\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\houfei-file\project\egg-example\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\houfei-file\project\egg-example\node_modules\co\index.js:65:19)
    at C:\houfei-file\project\egg-example\node_modules\co\index.js:54:5
    sql: INSERT INTO `userz`(`username`, `password`, `create-time`) VALUES('houfei', 'houfei429119', '2020-05-28 09:08:57.744')
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'egg-test.userz' doesn't exist"
sqlState: "42S02"
index: 0
sql: "INSERT INTO `userz`(`username`, `password`, `create-time`) VALUES('houfei', 'houfei429119', '2020-05-28 09:08:57.744')"
name: "unhandledRejectionError"
pid: 16980
hostname: LAPTOP-KV9DE7QA

2020-05-28 09:11:28,229 ERROR 18100 nodejs.unhandledRejectionError: ER_NO_SUCH_TABLE: Table 'egg-test.userz' doesn't exist
    at Query.Sequence._packetToError (C:\houfei-file\project\egg-example\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\houfei-file\project\egg-example\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\houfei-file\project\egg-example\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\houfei-file\project\egg-example\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\houfei-file\project\egg-example\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\houfei-file\project\egg-example\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\houfei-file\project\egg-example\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\houfei-file\project\egg-example\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\houfei-file\project\egg-example\node_modules\mysql\lib\Pool.js:199:23)
    at C:\houfei-file\project\egg-example\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\houfei-file\project\egg-example\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\houfei-file\project\egg-example\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\houfei-file\project\egg-example\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\houfei-file\project\egg-example\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\houfei-file\project\egg-example\node_modules\co\index.js:65:19)
    at C:\houfei-file\project\egg-example\node_modules\co\index.js:54:5
    sql: INSERT INTO `userz`(`username`, `password`, `create-time`) VALUES('houfei', 'houfei429119', '2020-05-28 09:11:28.216')
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'egg-test.userz' doesn't exist"
sqlState: "42S02"
index: 0
sql: "INSERT INTO `userz`(`username`, `password`, `create-time`) VALUES('houfei', 'houfei429119', '2020-05-28 09:11:28.216')"
name: "unhandledRejectionError"
pid: 18100
hostname: LAPTOP-KV9DE7QA

2020-05-28 10:19:32,759 ERROR 1572 nodejs.unhandledRejectionError: ER_NO_SUCH_TABLE: Table 'egg-test.userz' doesn't exist
    at Query.Sequence._packetToError (C:\houfei-file\project\egg-example\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\houfei-file\project\egg-example\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\houfei-file\project\egg-example\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\houfei-file\project\egg-example\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\houfei-file\project\egg-example\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\houfei-file\project\egg-example\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\houfei-file\project\egg-example\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\houfei-file\project\egg-example\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\houfei-file\project\egg-example\node_modules\mysql\lib\Pool.js:199:23)
    at C:\houfei-file\project\egg-example\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\houfei-file\project\egg-example\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\houfei-file\project\egg-example\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\houfei-file\project\egg-example\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\houfei-file\project\egg-example\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\houfei-file\project\egg-example\node_modules\co\index.js:65:19)
    at C:\houfei-file\project\egg-example\node_modules\co\index.js:54:5
    sql: INSERT INTO `userz`(`username`, `password`, `create-time`) VALUES('houfei002', 'houfei429119', '2020-05-28 10:19:32.755')
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'egg-test.userz' doesn't exist"
sqlState: "42S02"
index: 0
sql: "INSERT INTO `userz`(`username`, `password`, `create-time`) VALUES('houfei002', 'houfei429119', '2020-05-28 10:19:32.755')"
name: "unhandledRejectionError"
pid: 1572
hostname: LAPTOP-KV9DE7QA

2020-05-28 10:53:26,676 ERROR 18256 nodejs.EPERMError: EPERM: operation not permitted, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:127:28)
errno: -4048
syscall: "watch"
code: "EPERM"
filename: null
dir: "C:\\houfei-file\\project\\egg-example\\app\\service\\user"
name: "EPERMError"
pid: 18256
hostname: LAPTOP-KV9DE7QA

2020-05-28 13:34:35,694 ERROR 18256 nodejs.ClusterClientNoResponseError: client no response in 4393375ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\houfei-file\project\egg-example\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 18256
hostname: LAPTOP-KV9DE7QA

2020-05-28 17:06:39,662 ERROR 228 [-/127.0.0.1/-/19ms POST /auth/login] nodejs.Error: Invalid IV length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:103:19)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:121:20)
    at new Cipheriv (internal/crypto/cipher.js:225:22)
    at Object.createCipheriv (crypto.js:117:10)
    at Function.Encrypt (C:\houfei-file\project\egg-example\app\extend\utility\aes.js:34:25)
    at module.exports.login (C:\houfei-file\project\egg-example\app\controller\auth.js:7:38)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\houfei-file\project\egg-example\node_modules\egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\houfei-file\project\egg-example\node_modules\egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\houfei-file\project\egg-example\node_modules\egg-security\lib\middlewares\xssProtection.js:7:5)

pid: 228
hostname: LAPTOP-KV9DE7QA

2020-05-28 18:06:30,147 ERROR 3640 nodejs.ClusterClientNoResponseError: client no response in 3387024ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\houfei-file\project\egg-example\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 3640
hostname: LAPTOP-KV9DE7QA

2020-05-28 21:08:59,478 ERROR 3640 nodejs.ClusterClientNoResponseError: client no response in 10809318ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\houfei-file\project\egg-example\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 3640
hostname: LAPTOP-KV9DE7QA

2020-05-29 08:55:28,843 ERROR 3640 nodejs.ClusterClientNoResponseError: client no response in 42388195ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\houfei-file\project\egg-example\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 3640
hostname: LAPTOP-KV9DE7QA

